name: training workflow
run-name: Github actions first hand training
on: [push]
jobs:
  straight-forward-learning:
    runs-on: ubuntu-latest
    steps:
      - run: echo "were just training the workflow"
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
      
