name: training workflow
run-name: Github actions first hand training
on: [push]
jobs:
  straight-forward-learning:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - run: echo "were just training the workflow"
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
      
=======
      - run: echo "
>>>>>>> aafc7b847f8b506c073bc86a3420a8dcb241d32e
